Checking ingletons inequality for the W state on 6 qubits

In [2]:
from QIP import *
n=6
W_state_dict = {}
for i in range(n):
    bitstring = "0"*n
    bitstring = bitstring[:i] + '1' + bitstring[i+1:]
    W_state_dict[bitstring] = 1/n**.5
W_state = QCircuit(6,initial_state=bitstrings_to_vector(W_state_dict))
W_state.subsysem_analysis()
print("W state: "+state_as_string(W_state_dict))
# prints an empty list if ingletons never fails
print("Average failure saturation of ingletons inequality: "+str(W_state.ing["avg_fail_saturation"]))

W state: 0.408|100000> + 0.408|010000> + 0.408|001000> + 0.408|000100> + 0.408|000010> + 0.408|000001>
Average failure saturation of ingletons inequality: []


Checking Ingleton on the state $\ket{\psi}=\frac{1}{4}(\ket{0000}+\ket{1111}+\ket{1010}+\ket{1001})$

In [2]:
state_dict = {}
state_dict['0000']=1/4
state_dict['1111']=1/4
state_dict['1010']=1/4
state_dict['1001']=1/4
ing_test = QCircuit(4,initial_state=bitstrings_to_vector(state_dict))
ing_test.subsysem_analysis()
print("Average failure saturation of ingletons inequality: "+str(ing_test.ing["avg_fail_saturation"]))

Average failure saturation of ingletons inequality: []


Checking Ingleton using $\rho=\frac{1}{2}\ket{\psi}\bra{\psi}+\frac{1}{4}\ket{1010}\bra{1010}+\frac{1}{4}\ket{1001}\bra{1001}$, where $\ket{\psi}=\frac{1}{\sqrt{2}}(\ket{0000}+\bra{1111})$

In [70]:
psi_dict = {}
psi_dict["0000"]=1/2**.5
psi_dict["1111"]=1/2**.5
psi_vec = bitstrings_to_vector(psi_dict)
psi_vec.shape=(2**4,1)
vec1 = bitstrings_to_vector("1010")
vec1.shape=(2**4,1)
vec2 = bitstrings_to_vector("1001")
vec2.shape=(2**4,1)
rho = 0.5*np.outer(psi_vec,psi_vec.conj().T)+0.25*np.outer(vec1,vec1.conj().T)+0.25*np.outer(vec2,vec2.conj().T)
#rho = np.outer(psi_vec.conj(),psi_vec)

ing_test = QCircuit(4,pure_state=False)
ing_test.density_matrix=rho
ing_test.subsysem_analysis()
print("Average failure saturation of ingletons inequality: "+str(ing_test.ing["avg_fail_saturation"]))

Average failure saturation of ingletons inequality: [0.12255624891826573]


In [52]:
np.kron(bitstrings_to_vector("10"),bitstrings_to_vector("10"))


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [53]:
int("1010",2)

10

In [20]:
eigvals, eigvecs = np.linalg.eig(rho)
eigvals

array([1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [51]:
rho

array([[0.25, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
        0.  , 0.  , 0.  , 0.  , 0.25],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
        0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
        0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
        0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
        0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
        0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
        0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
        0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
        0.  , 0.  , 0.

In [68]:
def purify(rho):
    eigvals, eigvecs = np.linalg.eig(rho)
    dim = len(eigvecs)
    sum = 0.
    for i in range(dim):
        sum = sum + np.sqrt(eigvals[i])*np.kron(eigvecs[:,i],eigvecs[:,i])
    return sum

In [58]:
eigvals, eigvecs = np.linalg.eig(rho)

In [59]:
eigvals

array([0.5 , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.25,
       0.25, 0.  , 0.  , 0.  , 0.  ])

In [61]:
eigvecs[0]

array([ 0.70710678, -0.70710678,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ])

In [65]:
eigvecs[10]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

In [64]:
eigvecs[11]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.])

In [69]:
purified = np.outer(purify(rho),purify(rho).conj())
purified

array([[0.125, 0.   , 0.   , ..., 0.   , 0.   , 0.125],
       [0.   , 0.   , 0.   , ..., 0.   , 0.   , 0.   ],
       [0.   , 0.   , 0.   , ..., 0.   , 0.   , 0.   ],
       ...,
       [0.   , 0.   , 0.   , ..., 0.   , 0.   , 0.   ],
       [0.   , 0.   , 0.   , ..., 0.   , 0.   , 0.   ],
       [0.125, 0.   , 0.   , ..., 0.   , 0.   , 0.125]])

In [25]:
rho

array([[0.5, 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
        0. , 0. , 0.5],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
        0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
        0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
        0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
        0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
        0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
        0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
        0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
        0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
        0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0.

In [45]:
# my method for the partial trace, reorder the density matrix such that the bits to be traced out are at the end, then trace over second partition

def reorder_U(circuit_size,bits):
    """_summary_

    Args:
        circuit_size (int): number of bits in circuit
        bits (list): bits to move to the end

    Returns:
        ndarray: unitary permutation matrix which reorders the given bits
    """
    lgm = np.zeros((2**circuit_size,2**circuit_size))
    for bitint in range(2**circuit_size):
        bitstring = int_to_bitstring(bitint,circuit_size)
        transformed_bitstring = [bitstring[i] for i in range(len(bitstring)) if i not in bits] + [bitstring[i] for i in bits]
        row = np.array(1.)
        for bit in transformed_bitstring:
            row = np.kron(row,qubit_map[bit])
        lgm[bitint]=row
    return lgm

def partial_trace2(p,trace_out):
    """finds the reduced density matrix after tracing out the given indices

    Args:
        p (numpy.ndarray (2-d)): full density matrix
        trace_out (list): indices to trace out
    """
    d_b = len(trace_out)
    d_a = int(np.log2(np.shape(p)[0])) - d_b
    sum = 0
    for j in range(2**d_b):
        vec = np.zeros(2**d_b)
        vec[j]=1.
        vec.shape=(2**d_b,1)
        sum = sum + np.kron(np.eye(2**d_a),vec.conj().T)@reorder_U(d_b+d_a,trace_out).conj().T@p@reorder_U(d_b+d_a,trace_out)@np.kron(np.eye(2**d_a),vec)
        # sum = sum + np.kron(np.eye(2**d_a),vec.conj().T)@p@np.kron(np.eye(2**d_a),vec)
    return sum


In [18]:
partial_trace(purified,[1])

array([[0.5+0.j, 0. +0.j],
       [0. +0.j, 0.5+0.j]])

In [16]:
rho_test[rho_test!=0]

array([ 0.25+0.j, -0.25+0.j, -0.25+0.j,  0.25+0.j,  0.25+0.j,  0.25+0.j])

In [39]:
hw_state = {}
hw_state["011010"] = 1/3**.5
hw_state["110011"] = 1j/3**.5
hw_state["111111"] = -1/3**.5
psi_vec = bitstrings_to_vector(hw_state)
rho = np.outer(psi_vec,psi_vec.conj())
a = partial_trace(rho,[0,3])
a[a!=0]
#b = partial_trace(a,[2])
#b[b!=0]

array([0.33333333+0.j, 0.33333333+0.j, 0.33333333+0.j])

In [42]:
import qiskit.quantum_info as qi
hw_state = {}
hw_state["011010"] = 1/3**.5
hw_state["110011"] = 1j/3**.5
hw_state["111111"] = -1/3**.5
psi_vec = bitstrings_to_vector(hw_state)
rho = np.outer(psi_vec,psi_vec.conj())
a = qi.partial_trace(rho,[5,2]).data
a[a!=0]

array([0.33333333+0.j, 0.33333333+0.j, 0.33333333+0.j])

In [57]:
purify(rho)

array([ 0.35355339, -0.35355339,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        , -0.35355339,  0.35355339,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.  

In [71]:
purified_rho = np.outer(purify(rho),purify(rho).conj())
rho_test = qi.partial_trace(purified_rho,[4,5,6,7])
rho_test


DensityMatrix([[0.25+0.j, 0.  +0.j, 0.  +0.j, 0.  +0.j, 0.  +0.j,
                0.  +0.j, 0.  +0.j, 0.  +0.j, 0.  +0.j, 0.  +0.j,
                0.  +0.j, 0.  +0.j, 0.  +0.j, 0.  +0.j, 0.  +0.j,
                0.25+0.j],
               [0.  +0.j, 0.  +0.j, 0.  +0.j, 0.  +0.j, 0.  +0.j,
                0.  +0.j, 0.  +0.j, 0.  +0.j, 0.  +0.j, 0.  +0.j,
                0.  +0.j, 0.  +0.j, 0.  +0.j, 0.  +0.j, 0.  +0.j,
                0.  +0.j],
               [0.  +0.j, 0.  +0.j, 0.  +0.j, 0.  +0.j, 0.  +0.j,
                0.  +0.j, 0.  +0.j, 0.  +0.j, 0.  +0.j, 0.  +0.j,
                0.  +0.j, 0.  +0.j, 0.  +0.j, 0.  +0.j, 0.  +0.j,
                0.  +0.j],
               [0.  +0.j, 0.  +0.j, 0.  +0.j, 0.  +0.j, 0.  +0.j,
                0.  +0.j, 0.  +0.j, 0.  +0.j, 0.  +0.j, 0.  +0.j,
                0.  +0.j, 0.  +0.j, 0.  +0.j, 0.  +0.j, 0.  +0.j,
                0.  +0.j],
               [0.  +0.j, 0.  +0.j, 0.  +0.j, 0.  +0.j, 0.  +0.j,
                0.  +0.j, 0.  +0.j

Here I can see that under no permutation of tracing out 4 qubits does the reduced density matrix equal the original one

In [55]:
purified_rho = np.outer(purify(rho),purify(rho).conj())
for comb in combinations(range(8),4):
    rho_test = qi.partial_trace(purified_rho,list(comb))
    if np.allclose(rho_test,rho) == True:
        print(comb)

In [5]:
entropies_map = {}
subsystems = list(chain.from_iterable(n_partitioning(list(range(4)),2)))
subsystems.sort(key=len)
for subsystem in n_partitioning(list(range(4)),2):
    reduced_dm_A = partial_trace(rho,subsystem[1])
    reduced_dm_B = partial_trace(rho,subsystem[0])
    probs_A = np.linalg.eigvals(reduced_dm_A).tolist()
    probs_B = np.linalg.eigvals(reduced_dm_B).tolist()
    entropy_A = shannon_ent([p_i.real for p_i in probs_A])
    entropy_B = shannon_ent([p_i.real for p_i in probs_B])
    entropies_map[tuple(subsystem[0])] = entropy_A
    # S_A always = S_B if S_AB = 0 (S_AB is pure) so we dont waste time calculating it again
    entropies_map[tuple(subsystem[1])] = entropy_B

entropies_map


{(): -0.0,
 (0, 1, 2, 3): 1.039720770839918,
 (0,): 0.5623351446188083,
 (1, 2, 3): 1.3862943611198906,
 (1,): 0.5623351446188083,
 (0, 2, 3): 1.3862943611198906,
 (2,): 0.6931471805599453,
 (0, 1, 3): 1.3862943611198906,
 (3,): 0.6931471805599453,
 (0, 1, 2): 1.3862943611198906,
 (0, 1): 1.0397207708399179,
 (2, 3): 1.3862943611198906,
 (0, 2): 1.0397207708399179,
 (1, 3): 1.0397207708399179,
 (0, 3): 1.0397207708399179,
 (1, 2): 1.0397207708399179}

In [6]:
mutual_conditional([0],[1],[2],entropies_map)

-1.1102230246251565e-16

In [7]:
mutual_conditional([0],[1],[3],entropies_map)

-1.1102230246251565e-16

In [8]:
mutual([2],[3],entropies_map)

0.0

In [9]:
mutual([0],[1],entropies_map)

0.08494951839769871